INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View Access Log", "/iTrust/auth/patient/viewAccessLog.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient Edit My Demographics", "/iTrust/auth/patient/editMyDemographics.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View Full Calendar", "/iTrust/auth/patient/calendar.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View My Diagnoses", "/iTrust/auth/patient/myDiagnoses.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View My Lab Procedures", "/iTrust/auth/patient/viewMyLabProcedures.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View My Providers", "/iTrust/auth/patient/viewVisitedHCPs.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View Patient Specific Instructions", "/iTrust/auth/patient/viewPatientInstructions.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View My Expired Prescription Reports", "/iTrust/auth/patient/viewExpiredPrescriptionRecords.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View Immunization Report", "/iTrust/auth/patient/viewMyImmunizations.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View My Referrals", "/iTrust/auth/patient/viewPatientReferrals.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View Find an Expert", "/iTrust/auth/patient/findExpert.jsp", TRUE);
INSERT INTO features (feature_name, file_path, enabled) VALUES ("Patient View My Bills", "/iTrust/auth/patient/myBills.jsp", TRUE);